name: upload wheel with ci

on:
  workflow_dispatch:

jobs:
  build:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2019, macos-13, macos-14]
      fail-fast: false
    env:
      CIBW_BEFORE_BUILD: pip install -r requirements.txt
      CIBW_ARCHS_LINUX: "x86_64 aarch64"
      CIBW_ARCHS_WINDOWS: "AMD64 x86"
      CIBW_ARCHS_MACOS: "x86_64 universal2 arm64"
      CIBW_ENVIRONMENT: USE-CYTHON="1" USE-CFFI="1"
      CIBW_PROJECT_REQUIRES_PYTHON: ">=3.8"
    steps:
    - uses: actions/checkout@v4
    - name: Check out recursively
      run: git submodule update --init --recursive
    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Set up QEMU
      if: runner.os == 'Linux'
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all
    - name: Install cibuildwheel
      run: python -m pip install cibuildwheel==2.17.0 twine
    - name: Build wheels
      run: python -m cibuildwheel --output-dir wheelhouse
    - name: Publish package
      run: |
        twine upload ./wheelhouse/*.whl -u ${{ secrets.PYPI_USER }} -p ${{ secrets.PYPI_PASSWORD }}